### PR TITLE
Un-deprecate clone, make it not a liar about the root object

### LINKED ISSUE #163: Please do not remove clone option
Thx for great library, it works great. The only thing I am worried about is deprecating `clone`. I am using this library for merging 2 states inside redux. If some path of a merged object was not affected by merging, I need this object not to be copied, as then reference stays the same which is very important for optimisations like `PureComponent` in React or in `reselect`. To better put what I am talking about:

```js  
it('shoud not clone unchange objects', () => {
    const x = { y: { nested: 1, deeplyNested: { a: 100 } }, z: { nested: 2 } };
    const x2 = { y: { deeplyNested: { a: 101 } } };
    const x3 = merge(x, x2, { clone: false });
    expect(x3).toEqual({
      y: { nested: 1, deeplyNested: { a: 101 } },
      z: { nested: 2 },
    });
    expect(x).toEqual({
      y: { nested: 1, deeplyNested: { a: 100 } },
      z: { nested: 2 },
    });
    expect(x2).toEqual({ y: { deeplyNested: { a: 101 } } });
    expect(x.z).toBe(x3.z); // this would fail without clone option!
    expect(x.y).not.toBe(x3.y);
});
```

### LINKED ISSUE #186: Restore "clone" feature via new option : mergeWithTarget
I have this use case :

```js
import config from 'config.json';
import config_dev from 'config.dev.json';

if (env === 'dev') {
   merge( config, config_dev );
}

export default config;
```

my problem is that this module creates a `destination` object, and even if the docs has an old deprecated `clone` option, it has been removed anyway. I was expecting the same behavior as `Object.assign` but recursively with this module.

So, I propose to have this option re-inserted as a better alternative : `mergeWithTarget` with a default value of `false`.

Example usage: 

```js
import config from 'config.json';
import config_dev from 'config.dev.json';

if (env === 'dev') {
   merge( config, config_dev, { mergeWithTarget: true });
}

export default config;
```

Because sometimes there is no need to create 3 objects when 2 is perfectly acceptable.

### LINKED ISSUE #208: Merging objects discards target class information
For my use case, I am serializing JSON to ES6 classes to assist in control flow and developer experience. I am using `deepmerge` to update objects stored in Easy Peasy, and I noticed that merging is causing the class information to be discarded, which is breaking my downstream use of `instanceof` for control flow purposes as well as likely confusing Easy Peasy / immer with new memory pointers for objects in state.

Specifically, this is where the issue lies in `mergeObject`:
```
	// This is causing type information to be discarded on merge
	var destination = {}
```
☝️ If I change this to assign the value of `target` to `destination` it works as I expect it to, but breaks other use cases.

I added the following unit test to show the behavior I expect, and it fails as I described above.
```
test('result should retain target type information', function(t) {
	var src = { key1: 'value1', key2: 'value2' }
	class CustomType {}
	var target = new CustomType()

	var res = merge(target, src)
	t.not(src instanceof CustomType)
	t.assert(target instanceof CustomType)
	t.assert(res instanceof CustomType) // <--- this is the failure point
	t.end()
})
```
Is this something that would be considered for support in the future?

### LINKED ISSUE #212: New "clone" behavior
## Overview

1. Make the current behavior when the "clone" flag is set to `false` the default behavior.
2. Un-deprecate the "clone" flag or introduce a new flag (maybe called "deepClone") that when `true`, will perform the current default behavior.
3. Introduce a new flag called "mergeWithTarget" that when `true`, will result in the target (first parameter) being mutated as a result of the merge. No value is returned when operating in this mode.

### 1. No clone by default

The library is called "deep merge" not "deep merge and clone" so it doesn't make sense to deep clone out of the box by default. Cloning adds a lot of overhead and most of the time isn't needed.

re: #163

### 2. Still allow cloning

Cloning while merging is still something that is definitely valid and there should be an option to perform this behavior.

### 3. Allow in-place merging

Some times a new object isn't wanted at all; instead a changes to an object want to me merged in place.

re: #186

There is already an open PR that adds this behavior to the "clone" flag. #209
But the issue with having this behavior on the "clone" flag is that it that it is valid to want to both want to "clone" and not mutate the any of the parameters.

## PS

@TehShrike I can implementing feature 1 and 2 if you like.
@creativeux Do you think you could update #209 to put the in-place merging behind a new "mergeWithTarget" flag? Pending @TehShrike's approval.

I'll also be able to implement these changes into the typings I'm working on in #211.

## PPS

@TehShrike While working on #211 I noticed that structure of this project is a bit out of date. Would you like me to also work on modernizing it?

Proposal of things of the top of my head:

- Add eslint
- Refactor code into multiple files - these files will live in a "src/" directory.
- Update rollup and other dev dependencies
- Switch to using TypeScript

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #208
Potentially fixes #186
Fixes #163
Potentially fixes #212

### CODE REVIEW

**Comment by TehShrike** [comment]
Going back to #209 I was having trouble parsing it all – is there anything missing from the implementation in this pull request here?

**Comment by RebeccaStevens** [comment]
I think this is all good to be merged.

I don't think it fully addresses #186 or #212 though, I'll work on them after this (and my typescript work) is merged.

**Comment by TehShrike** [comment]
Yeah, #186 and #212 both also described other new behaviors, but I'm not sure that any of those other new behaviors are actually a good idea to implement, and I'd want to talk a lot more before moving forward with any of them.

But I am solidly on board with undeprecating `clone` and making it apply to the target root.

**Comment by lipnitsk** [comment]
@TehShrike are you planning on releasing v5 anytime soon?

**Comment by RebeccaStevens** [comment]
@lipnitsk There's no current timeline for v5's release. In the mean time I recommend using [deepmerge-ts](https://www.npmjs.com/package/deepmerge-ts).

**Pull request merged**
